spring.application.name=COLLEGE-MANAGEMENT-SERVICE
server.port=9090


# ===============================
# DATABASE CONFIG FOR PRO
# ===============================

#spring.datasource.url=jdbc:mysql://localhost:3306/college
spring.datasource.url=jdbc:mysql://localhost:3306/college 	
spring.datasource.username=root
spring.datasource.password=Gopu@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.batch.jdbc.initialize-schema=never

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.in.gopal.college=DEBUG
logging.file.name=college-application.log

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=my-super-secret-key-my-super-secret-key-123456
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ===============================
# SWAGGER (Optional but Recommended)
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# EUREKA CLIENT CONFIG
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Optional (for file serving later)
spring.web.resources.static-locations=file:uploads/

#==========================
#          AWS
#==========================
#aws.access-key=YOUR_ACCESS_KEY
#aws.secret-key=YOUR_SECRET_KEY
#aws.region=ap-south-1

#==========================
#       RAZORPAY
#========================== 
razorpay.key.id=rzp_test_Su32efnP9UJqZQ
razorpay.key.secret=Uis27br0gyvTeUNfDBTeTQtX