spring.application.name=COLLEGE-MANAGEMENT-SERVICE
server.port=9090

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/college}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.batch.jdbc.initialize-schema=never

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.in.gopal.college=DEBUG
logging.file.name=college-application.log

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# EUREKA CLIENT CONFIG
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.web.resources.static-locations=file:uploads/

# ===============================
# RAZORPAY
# ===============================
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}